apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgwatch2.fullname" . }}-initdb
data:
  00_initdb.sql: |
    CREATE ROLE {{ .Values.postgresql.user | default "pgwatch2" }} WITH LOGIN PASSWORD '{{ .Values.postgresql.password | default "pgwatch2" }}';
  01_initdb.sql: |
    CREATE DATABASE {{ .Values.postgresql.database | default "pgwatch2" }} OWNER {{ .Values.postgresql.user | default "pgwatch2" }};
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.postgresql.database | default "pgwatch2" }} TO {{ .Values.postgresql.user | default "pgwatch2" }};
  02_initdb.sql: |
    CREATE DATABASE {{ .Values.postgres_storage.database | default "pgwatch2_metrics" }} OWNER {{ .Values.postgresql.user | default "pgwatch2" }};
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.postgres_storage.database | default "pgwatch2_metrics" }} TO {{ .Values.postgresql.user | default "pgwatch2" }};
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgwatch2.fullname" . }}-influxdb-init
data:
  influxdb-init.iql: |
    CREATE DATABASE {{ .Values.influxdb.database | default "pgwatch2" }};
    CREATE RETENTION POLICY pgwatch_def_ret ON {{ .Values.influxdb.database | default "pgwatch2" }} DURATION 30d REPLICATION 1 DEFAULT;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgwatch2.fullname" . }}-env
{{- with .Values.daemon.env }}
data:
{{ toYaml . | indent 2 }}
{{- end }}
