{{- if eq .Values.pgwatch.grafana.enable_grafana "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: pgwatch
    pgwatch.pods.role: grafana
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      application: pgwatch
      pgwatch.pods.role: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: pgwatch
        pgwatch.pods.role: grafana
    spec:
      containers:
        - env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
              value: /var/lib/grafana/dashboards/1-global-db-overview.json
          #  - name: GF_INSTALL_PLUGINS
          #    value: marcusolsson-treemap-panel
            {{- if eq .Values.pgwatch.postgres.create_metric_database "true" }} 
            - name: GF_DATABASE_TYPE
              value: postgres
            - name: GF_DATABASE_HOST
              value: postgres-svc:5432
            - name: GF_DATABASE_NAME
              value: pgwatch_grafana
            - name: GF_DATABASE_SSL_MODE
              value: disable
            - name: GF_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: pgwatch-postgresql-secret-pgwatch
                  key: username
            - name: GF_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgwatch-postgresql-secret-pgwatch
                  key: password
            {{- else }}
            - name: GF_DATABASE_TYPE
              value: postgres
            - name: GF_DATABASE_HOST
              value: {{ .Values.pgwatch.postgres.use_existing_database.endpoint }}
            - name: GF_DATABASE_NAME
              value: {{ .Values.pgwatch.postgres.use_existing_database.database }}
            - name: GF_DATABASE_SSL_MODE
              value: {{ .Values.pgwatch.postgres.use_existing_database.sslmode }}
            - name: GF_DATABASE_USER
              value: {{ .Values.pgwatch.postgres.use_existing_database.username }}
            - name: GF_DATABASE_PASSWORD
              value: {{ .Values.pgwatch.postgres.use_existing_database.password }}
            {{- end }}
          image: {{ .Values.pgwatch.grafana.image }}
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/datasources/pg_ds.yml
              name: grafana-datasources
              subPath: pg_ds.yml
            - mountPath: /etc/grafana/provisioning/dashboards/dashboards_provider.yml
              name: grafana-dashboard-config
              subPath: dashboards_provider.yml
            - mountPath: /var/lib/grafana/dashboards
              name: grafana-dashboards
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: postgres_datasource.yml
                path: pg_ds.yml
            name: grafana-datasources
          name: grafana-datasources
        - name: grafana-dashboard-config
          configMap:
            name: grafana-dashboard-config
        - name: grafana-dashboards
          projected:
            defaultMode: 416
            sources:
              {{- if eq .Values.pgwatch.postgres.enable_pg_sink "true" }}
              {{- range $path, $_ := .Files.Glob "dashboards/postgresql/*.json" }}
              - configMap:
                  name: "grafana-postgresql-dashboard-{{ base $path | lower | replace "." "-" | replace "_" "-" }}"
                  items:
                    - key: {{ base $path }}
                      path: "postgresql/{{ base $path }}"
              {{- end }}
              {{- end }}

              {{- if eq .Values.pgwatch.prometheus.enable_prom_sink "true" }}
              {{- range $path, $_ := .Files.Glob "dashboards/prometheus/*.json" }}
              - configMap:
                  name: "grafana-prometheus-dashboard-{{ base $path | lower | replace "." "-" | replace "_" "-" }}"
                  items:
                    - key: {{ base $path }}
                      path: "prometheus/{{ base $path }}"
              {{- end }}
              {{- end }}       
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    application: pgwatch
  name: grafana-datasources
  namespace: {{ .Release.Namespace }}
data:
  postgres_datasource.yml: |
    apiVersion: 1
    datasources:
  {{- if eq .Values.pgwatch.postgres.enable_pg_sink "true" }}
  {{- if eq .Values.pgwatch.postgres.create_metric_database "true" }} 
    - name: pg-metrics
      type: postgres
      url: postgres-svc:5432
      access: proxy
      password: pgwatchadmin
      user: pgwatch
      database: pgwatch_metrics
      basicAuth: true
      isDefault: true
      jsonData:
        sslmode: disable
      postgresVersion: 1700
      version: 1
      editable: true
  {{- else }}
    - name: pg-metrics
      type: postgres
      url: {{ .Values.pgwatch.postgres.use_existing_database.endpoint }}:{{ .Values.pgwatch.postgres.use_existing_database.port }}
      access: proxy
      password: {{ .Values.pgwatch.postgres.use_existing_database.password }}
      user: {{ .Values.pgwatch.postgres.use_existing_database.username }}
      database: {{ .Values.pgwatch.postgres.use_existing_database.database }}
      basicAuth: true
      isDefault: true
      jsonData:
        sslmode: {{ .Values.pgwatch.postgres.use_existing_database.sslmode | default "disable" }}
      version: 1
      editable: true
  {{ end }}
  {{ end }}
  {{- if eq .Values.pgwatch.prometheus.enable_prom_sink "true" }}
    - name: PROMETHEUS
      type: prometheus
      access: proxy
      orgId: 1
      url: http://pgwatch-prometheus-svc:9090
      password:
      user:
      database:
      basicAuth:
      basicAuthUser:
      basicAuthPassword:
      withCredentials:
      {{- if eq .Values.pgwatch.postgres.enable_pg_sink "false" }}
      isDefault: true
      {{- end}}
      version: 1
      editable: false
  {{ end }}
{{ end }}