apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "pgwatch.commonLabels" (dict "root" . "component" "pgwatch") | nindent 4 }}
  name: pgwatch
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pgwatch.selectorLabels" (dict "root" . "component" "pgwatch") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgwatch.commonLabels" (dict "root" . "component" "pgwatch") | nindent 8 }}
    spec:
      {{- include "pgwatch.podSecurityContext" (dict "global" .Values.securityContext "component" .Values.pgwatch.securityContext) | nindent 6 }}
      containers:
        - env:
          - name: PGWATCH_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "pgwatch.credentialSecretName" . }}
                key: {{ include "pgwatch.credentialUsernameKey" . }}
          - name: PGWATCH_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "pgwatch.credentialSecretName" . }}
                key: {{ include "pgwatch.credentialPasswordKey" . }}
        {{- if include "pgwatch.isTrue" (include "pgwatch.postgres.createMetricDatabase" .) }}
          - name: METRIC_DATABASE_ENDPOINT
            value: "{{ include "pgwatch.dbHost" . }}.{{ .Release.Namespace }}.svc.cluster.local"
          - name: METRIC_DATABASE_PORT
            value: "5432"
          - name: METRIC_DATABASE_DATABASE
            value: pgwatch_metrics
          - name: METRIC_DATABASE_SSLMODE
            value: disable
        {{- else if (include "pgwatch.postgres.hasUseExistingDatabase" .) }}
          - name: METRIC_DATABASE_ENDPOINT
            value: {{ (include "pgwatch.postgres.useExistingDatabase.endpoint" .) }}
          - name: METRIC_DATABASE_PORT
            value: "{{ (include "pgwatch.postgres.useExistingDatabase.port" .) }}"
          - name: METRIC_DATABASE_DATABASE
            value: {{ (include "pgwatch.postgres.useExistingDatabase.database" .) }}
          - name: METRIC_DATABASE_SSLMODE
            value: {{ (include "pgwatch.postgres.useExistingDatabase.sslmode" .) }}
        {{ end }}
        {{- if include "pgwatch.isTrue" (include "pgwatch.postgres.enablePgSink" .) }}
          - name: PG_IS_SINK
            value: "true"
          - name: PG_RETENTION_DAYS
            value: "{{ (include "pgwatch.postgres.settings.retentionDays" .) }} days"
        {{ end }}
        {{- if include "pgwatch.isTrue" (include "pgwatch.prometheus.enablePromSink" .) }}
          - name: PROM_IS_SINK
            value: "true"
        {{ end }}
        {{- if and .Values.pgwatch.ingress.enabled .Values.pgwatch.ingress.webBasePath }}
          - name: PW_WEBBASEPATH
            value: {{ .Values.pgwatch.ingress.webBasePath | quote }}
        {{- end }}
        {{- range $key, $value := .Values.pgwatch.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
        {{- end }}
        {{- if .Values.pgwatch.sources.files }}
          - name: PW_SOURCES
            value: "/tmp/pgwatch-sources"
        {{- else }}
          - name: PW_SOURCES
            value: "postgresql://$(PGWATCH_USER):$(PGWATCH_USER_PASSWORD)@$(METRIC_DATABASE_ENDPOINT):$(METRIC_DATABASE_PORT)/$(METRIC_DATABASE_DATABASE)?sslmode=$(METRIC_DATABASE_SSLMODE)"
        {{- end }}
        {{- with .Values.pgwatch.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          image: {{ .Values.pgwatch.image }}:{{ .Chart.AppVersion }}
          volumeMounts:
          - name: launcher
            mountPath: /tmp/launcher.sh
            subPath: launcher.sh
          {{- if .Values.pgwatch.sources.files }}
          - name: pgwatch-sources
            mountPath: /tmp/pgwatch-sources/
          {{- end }}
          name: pgwatch
          ports:
            - containerPort: {{ .Values.pgwatch.webPort }}
              protocol: TCP
        {{- if include "pgwatch.isTrue" (include "pgwatch.prometheus.enablePromSink" .) }}
            - containerPort: 9188
              protocol: TCP
        {{ end }}
          command: ["/tmp/launcher.sh"]
          {{- include "pgwatch.containerSecurityContext" (dict "global" .Values.securityContext "component" .Values.pgwatch.securityContext) | nindent 10 }}
      volumes:
      - name: launcher
        configMap:
          name: pgwatch-cm
          defaultMode: 0777  # Damit es direkt ausführbar ist
      {{- if .Values.pgwatch.sources.files }}
      - name: pgwatch-sources
        configMap:
          name: pgwatch-sources-cm
      {{- end }}
      restartPolicy: Always
