apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "pgwatch.commonLabels" (dict "root" . "component" "pgwatch") | nindent 4 }}
  name: pgwatch
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pgwatch.selectorLabels" (dict "root" . "component" "pgwatch") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgwatch.commonLabels" (dict "root" . "component" "pgwatch") | nindent 8 }}
    spec:
      {{- include "pgwatch.podSecurityContext" (dict "global" .Values.securityContext "component" .Values.pgwatch.securityContext) | nindent 6 }}
      containers:
        - env:
          {{- include "pgwatch.pgwatch.env" . | nindent 10 }}
        {{- with .Values.pgwatch.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- if kindIs "string" .Values.pgwatch.image }}
          image: {{ .Values.pgwatch.image }}
        {{- else }}
          image: {{ .Values.pgwatch.image.repository }}:{{ .Values.pgwatch.image.tag | default .Chart.AppVersion }}
        {{- end }}
        {{- with .Values.pgwatch.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          volumeMounts:
          - name: launcher
            mountPath: /tmp/launcher.sh
            subPath: launcher.sh
          {{- if .Values.pgwatch.sources.files }}
          - name: pgwatch-sources
            mountPath: /tmp/pgwatch-sources/
          {{- end }}
          name: pgwatch
          ports:
            - containerPort: {{ .Values.pgwatch.webPort }}
              protocol: TCP
        {{- if include "pgwatch.isTrue" (include "pgwatch.prometheus.enablePromSink" .) }}
            - containerPort: 9188
              protocol: TCP
        {{ end }}
          command: ["/tmp/launcher.sh"]
          {{- include "pgwatch.containerSecurityContext" (dict "global" .Values.securityContext "component" .Values.pgwatch.securityContext) | nindent 10 }}
      volumes:
      - name: launcher
        configMap:
          name: pgwatch-cm
          defaultMode: 0777  # Damit es direkt ausführbar ist
      {{- if .Values.pgwatch.sources.files }}
      - name: pgwatch-sources
        configMap:
          name: pgwatch-sources-cm
      {{- end }}
      restartPolicy: Always
