{{- if include "pgwatch.isTrue" (include "pgwatch.prometheus.newPrometheus.createPrometheus" .) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "pgwatch.commonLabels" (dict "root" . "component" "prometheus") | nindent 4 }}
  name: prometheus-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ (include "pgwatch.prometheus.newPrometheus.volume.size" .) }}
  storageClassName: {{ (include "pgwatch.prometheus.newPrometheus.volume.storageClass" .) }}
{{ end }}
